# Generated by Django 5.0.7 on 2025-03-20 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_created_at_alter_project_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('لم يبدأ بعد', 'لم يبدأ بعد'), ('قيد التنفيذ', 'قيد التنفيذ'), ('مكتمل', 'مكتمل'), ('معلق', 'معلق')], default='لم يبدأ بعد', max_length=20, verbose_name='حالة المشروع'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='WhatsApp Number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
